function [slider, leftNote, rightNote] = makeSlider(initval, minval, maxval, xpos, ypos, len, name, minStr, maxStr,callback)
slider = uicontrol('Parent',gcf,'Style','slider','Units','normalized',...
    'Position',[xpos ypos len 0.03],'value', initval, 'min', minval, 'max', maxval);
addlistener(slider, 'Value', 'PostSet', callback);
leftNote = annotation(gcf,'textbox','String', minStr, 'FontSize',12,'units','normalized',...
    'Position', [xpos-0.05 ypos 0.05 0.03],'Interpreter','Tex','EdgeColor','none',...
    'HorizontalAlignment','center','VerticalAlignment','middle');
rightNote = annotation(gcf,'textbox','String', maxStr, 'FontSize',12,'units','normalized',...
    'Position', [xpos+len ypos 0.05 0.03],'Interpreter','Tex','EdgeColor','none',...
    'HorizontalAlignment','center','VerticalAlignment','middle');
annotation(gcf,'textbox','String', name, 'FontSize',12,'units','normalized',...
    'Position', [0 ypos 0.05 0.03],'Interpreter','Tex','EdgeColor','none',...
    'HorizontalAlignment','center','VerticalAlignment','middle');
end